Tron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('server.urls')),
    path('chat/', include('chat.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('', show_index, name='home'),
    path('login', show_login, name='login'),
    path('register', show_register, name='register'),
    path('chat', show_chat, name='chat'),
    path('profile', show_profile, name='profile'),
    path('tariffs', show_tariffs, name='tariffs'),
    path('detail_tariff', show_detail_tariff, name='detail_tariff'),
    path('tariff_user', show_tariff_user, name='tariff_user'),
    path('update_tariff/<int:pk>', update_tariff, name='update_tariff'),
    path('update_tariff_internal_cash_account/<int:pk>', update_tariff_internal_cash_account,
         name='update_tariff_internal_cash_account'),
    path('detail_report', show_detail_report, name='detail_report'),
    path('tariff_buy/<int:pk>', show_tariff_buy, name='tariff_buy'),
    path('payments_tariff/<int:pk>', payments_tariff, name='payments_tariff'),
    path('payments_tariff_internal_cash_account/<int:pk>', payments_tariff_internal_cash_account,
         name='payments_tariff_internal_cash_account'),
    path('report_category', show_report_category, name='report_category'),
    path('admin_tariff', show_admin_tariff, name='admin_tariff'),
    path('payment_history', show_payment_history, name='payment_history'),
    path('adding_funds', adding_funds, name='adding_funds'),
    path('referral_program', show_referral_program, name='referral_program'),
    path('set-idf-form', show_form_idf, name='set-idf-form'),
    path('cat_news', show_cat_news, name='cat_news'),
    path('news/<int:pk>', show_news, name='news'),
    path('detail_news/<int:pk>', show_detail_news, name='detail_news'),
    path('auth_flesh', auth_flesh, name='auth_flesh'),
    path('write_key_idf', write_idf_key, name='write_key_idf'),
    path('del_idf_connect', del_idf_connect, name='del_idf_connect'),
    path('online_connection_idf', online_connection_idf, name='online_connection_idf')
    #todo создать доп анонимный чат для передачи ключей


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Tariff(models.Model):
    class Meta:
        verbose_name = 'Тариф'
        verbose_name_plural = 'Тарифы'

    MARKET_FIELD = [
        ("on sale", "В продаже"),
        ('popular', 'Популярный'),
        ("unavailable", "Недоступен"),
        ("in processing", "В разработке"),
        ("new", "Новинка"),
        ("beneficial", "Выгодный"),

    ]

    LICENSES_FIELD = [
        ("base", "Базовый"),
        ('professionale', 'Для организаций'),
        ("premium", "Партнерам"),
    ]

    category_market = models.CharField(verbose_name='Маркетинговое положение', choices=MARKET_FIELD, max_length=30)
    name = models.CharField(verbose_name='Название лицензии',  max_length=20)
    dsc = models.TextField(verbose_name='Описание', default='Описание отсутствует', blank=True, null=True)
    count_msg = models.IntegerField(verbose_name='Количество сообщений')
    count_dialog = models.IntegerField(verbose_name='Количество диалогов', default=1)
    count_invited_user = models.IntegerField(verbose_name='Количество приглашенных пользователей')
    count_withdrawal = models.IntegerField(verbose_name='Вывод средств', default=30000)
    mess_ln = models.IntegerField(verbose_name='Длина сообщения')
    delay = models.IntegerField(verbose_name='Задержка', default=5)
    deg_protection = models.IntegerField(verbose_name='Степень защиты')
    name_license = models.CharField(verbose_name='Лицензия', choices=LICENSES_FIELD, max_length=20, default=LICENSES_FIELD[0])
    price = models.IntegerField(verbose_name='Стоимость', default=0, null=True, blank=True)
    price_update = models.IntegerField(verbose_name='Стоимость продления', default=0,)
    financial_constraints = models.ForeignKey('FinancialConstraints', verbose_name='Коммиссия на платежные операции',
                                   on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class FinancialConstraints(models.Model):
    class Meta:
        verbose_name = 'Коммиссия'
        verbose_name_plural = 'Коммиссии'

    LICENSES_FIELD = [
        ("base", "Базовый"),
        ("base+", "Базовый+"),
        ('professionale', 'Для организаций'),
        ('professionale+', 'Для организаций+'),
        ("premium", "Партнерам"),
        ("premium+", "Партнерам+"),
        ("premium++", "Партнерам++"),
    ]

    name = models.CharField(verbose_name='Наименование', choices=LICENSES_FIELD, max_length=20)
    percentage_withdrawal = models.IntegerField(verbose_name='Процент на вывод')
    percentage_admission = models.IntegerField(verbose_name='Процент на пополнение')
    withdrawal_amount_min = models.IntegerField(verbose_name='Минимальная сумма вывода')
    withdrawal_amount_max = models.IntegerField(verbose_name='Максимальная сумма вывода')
    deposits_min = models.IntegerField(verbose_name='Минимальная сумма зачислений')
    deposits_max = models.IntegerField(verbose_name='Максимальная сумма зачислений')
    reward_ref = models.IntegerField(verbose_name='Вознаграждение за рефералов', default=1)

    def __str__(self):
        return self.name


class UserCustom(AbstractUser):
    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    STATUS_IDF_FIELDS = [
        ('not_connect', 'Не подключен'),
        ('waiting', 'В ожидании'),
        ('connected', 'Подключен')
    ]

    flesh = models.ForeignKey('Flesh', verbose_name='ID флешки', on_delete=models.CASCADE, default=None, null=True, blank=True)
    is_active_flesh = models.BooleanField(verbose_name='Активность аккаунта', default=True)
    rif_token = models.CharField(verbose_name='Реферальный токен', max_length=20)
    photo = models.ImageField(verbose_name='Фотография', upload_to='user/photo/%Y/%m/%d/', null=True, blank=True)
    payments = models.ManyToManyField('Payment',  verbose_name='Платежные операции', null=True, blank=True)
    balance_tariff = models.ForeignKey('TariffBalances', verbose_name='Остаток тарифа', on_delete=models.PROTECT, null=True, blank=True)
    status_idf = models.CharField(verbose_name='Статус подключения', choices=STATUS_IDF_FIELDS, max_length=20, default='not_connect')
    identification_dialog = models.ForeignKey('ObjIdfDialog', verbose_name='Объект индификации диалога',  blank=True, null=True, on_delete=models.PROTECT)

    status_connection = models.ForeignKey('ConnectIDF', verbose_name='Статус подключения', on_delete=models.PROTECT,
                                          blank=True, null=True)
    internal_cash_account = models.IntegerField(verbose_name='Внутренний счет', default=0)
    technical_comment = models.CharField(verbose_name='Технический комментарий', max_length=20, blank=True, null=True)
    reference_user = models.ForeignKey('UserCustom', verbose_name='Реферанс', on_delete=models.PROTECT, blank=True, null=True)



class Flesh(models.Model):
    class Meta:
        verbose_name = 'Флешка'
        verbose_name_plural = 'Флешки'

    IDF = models.CharField(verbose_name='ИДФ', max_length=500)
    private_code = models.CharField(verbose_name='Приватный ключ', max_length=30, blank=True, null=True)
    is_active = models.BooleanField(verbose_name='Активно', default=False)
    tariff = models.ForeignKey(Tariff, verbose_name='Тариф', on_delete=models.PROTECT)
    is_use_user = models.BooleanField(verbose_name='Используется?', default=False)
    count_flesh = models.IntegerField(verbose_name='Остаток флешек', default=0)
    price = models.IntegerField(verbose_name='Стоимость', default=0)
    auth_chat = models.BooleanField(verbose_name='Авторизация флешки', default=False)
    is_save_key = models.BooleanField(verbose_name='Локальное хранилище', default=False)

    def __str__(self):
        return self.IDF


class TariffBalances(models.Model):
    class Meta:
        verbose_name = 'Баланс тарифа'
        verbose_name_plural = 'Балансы тарифов'

    count_msg_user = models.IntegerField(verbose_name='Количество отправленных сообщений', default=0)
    count_invited_user = models.IntegerField(verbose_name='Количество приглашенных пользователей', default=1)
    count_msg = models.IntegerField(verbose_name='Количество сообщений')
    count_dialog = models.IntegerField(verbose_name='Количество диалогов', default=1)
    interlocutors = models.ManyToManyField(UserCustom, verbose_name='Собеседники', blank=True, null=True)
    count_withdrawal = models.IntegerField(verbose_name='Сумма вывода', default=1000)
    data_start = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    data_update = models.DateField(verbose_name='Дата обновления', auto_now=True)




class Payment(models.Model):
    class Meta:
        verbose_name = 'Платежная операция'
        verbose_name_plural = 'Платежные операции'

    CAT_FIELD = [
        ('purchase', 'Покупка'),
        ('update', 'Обновление'),
        ('purchase_bonuses', 'Оплата бонусами'),
        ('enrollment', 'Зачисление'),
        ('withdrawal', 'Вывод средств'),
        ('replenishment', 'Пополнение')
    ]

    STATUS_FIELD = [
        ('processing', 'В обработке'),
        ('checking', 'На проверке'),
        ('waiting', 'В ожидании'),
        ('successful', 'Успешный'),
        ('rejected', 'Отклонен'),
        ('return', 'Возврат'),
        ('unsuccessful', 'Неуспешный'),
        ('blocked', 'Заблокирован'),
        ('canceled', 'Отменен'),
        ('processed', 'Обработан'),
    ]

    category = models.CharField(verbose_name='Категория операции', max_length=30, choices=CAT_FIELD)
    dsc = models.CharField(verbose_name='Комментарий', max_length=155)
    price_start = models.IntegerField(verbose_name='Первоначальная цена', blank=True, null=True, default=0)
    percent_price = models.IntegerField(verbose_name='Процент операции', blank=True, null=True, default=0)
    price = models.IntegerField(verbose_name='Стоимость', default=0)
    status = models.CharField(verbose_name='Статус операции', max_length=30, choices=STATUS_FIELD,
                              default='waiting', blank=True, null=True)
    tech_msg = models.CharField(verbose_name='Внутренний комментарий', max_length=100, blank=True, null=True)
    date = models.DateTimeField(verbose_name='Дата операции', auto_now_add=True)
    technical_comment = models.CharField(verbose_name='Технический комментарий', max_length=20, blank=True, null=True)
    tariff = models.ForeignKey(Tariff, verbose_name='Приобретаемый тариф', on_delete=models.PROTECT, blank=True, null=True)
    reference = models.ForeignKey('UserCustom', verbose_name='Реферанс', on_delete=models.PROTECT, null=True, blank=True)


class KeyIdentification(models.Model):
    class Meta:
        verbose_name = 'Индификация ключа'
        verbose_name_plural = 'Индификация ключей'

    token_dialog = models.CharField(verbose_name='Токен авторизации диалога', max_length=20)
    f_key = models.CharField(verbose_name='Первый ключ(любой смивол)', max_length=1)
    s_key = models.CharField(verbose_name='Второй ключ(любая цифра)', max_length=3)
    image_key = models.ImageField(verbose_name='Картинка', upload_to='user/key/img_key/%Y/%m/%d/', null=True, blank=True)
    is_active = models.BooleanField(verbose_name='Актуальный')
    date_update = models.DateTimeField(verbose_name='Последнее обновление', auto_now_add=True)

    def __str__(self):
        return self.token_dialog


class CatNews(models.Model):
    class Meta:
        verbose_name = 'Категория новости'
        verbose_name_plural = 'Категории новостей'

    title = models.CharField(verbose_name='Категория', max_length=155)

    def __str__(self):
        return self.title


class News(models.Model):
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    CAT_FIELD = [
        ('new', 'Новинка'),
        ('product', 'О продукте'),
        ('support', 'О сервисе'),
        ('tariff', 'О тарифах')
    ]

server/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import UserCustom


class RegistrationForm(forms.Form):
    user_flesh_id = forms.CharField(label='Индификатор пользователя', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите IDF'}))
    username = forms.CharField(label='Придумайте логин', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Придумайте логин'}))
    password = forms.CharField(label='Придумайте пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Придумайте пароль'}))
    confirm_password = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}))

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if UserCustom.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с таким логином уже существует')
        return username


class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите логин'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))


class ChatAuthenticationForm(forms.Form):
    token = forms.CharField(label='Аунтификация чата', max_length=20, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Токен должен состоять из 20 символов',
               'autocomplete': 'off'}))
    first_key = forms.CharField(label='Первый ключ', max_length=1, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Любой символ, кроме цифры', 'autocomplete': 'off'}))
    second_key = forms.CharField(label='Второй ключ', max_length=3, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Любая цифра', 'autocomplete': 'off'}))
    image = forms.ImageField(label='Загрузить изображение', required=False)

    def clean_token(self):
        token = self.cleaned_data.get('token')
        if not token or len(token) != 20:
            raise ValidationError('Токен должен состоять из 20 символов')
        return token

    def clean_first_key(self):
        first_key = self.cleaned_data.get('first_key')
        if not first_key.isalpha():
            raise ValidationError('Первый ключ должен содержать только буквы')
        return first_key

    def clean_second_key(self):
        second_key = self.cleaned_data.get('second_key')
        if not second_key.isdigit():
            raise ValidationError('Второй ключ должен быть цифрой')
        return second_key


class SupportForm(forms.Form):
    name = forms.CharField( max_length=155, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Напишите ваше имя',
               'autocomplete': 'off'}))
    mail = forms.EmailField( max_length=155, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Напишите вашу почту', 'autocomplete': 'off'}))
    dsc = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Опишите вашу проблему', 'autocomplete': 'off'}))
    category = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': "hidden", 'value': 'Problems_with_site', 'placeholder': 'Ваша категория', 'autocomplete': 'off'}))


class CatSupportForm(forms.Form):
    category_site = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': "hidden", 'value': 'Problems_with_site',
               'placeholder': 'Ваша категория', 'autocomplete': 'off'}))
    category_idf = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': "hidden", 'value': 'Problems_with_IDF',
               'placeholder': 'Ваша категория', 'autocomplete': 'off'}))
    category_money = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': "hidden", 'value': 'Problems_with_money',
               'placeholder': 'Ваша категория', 'autocomplete': 'off'}))
    category_other = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': "hidden", 'value': 'Other',
               'placeholder': 'Ваша категория', 'autocomplete': 'off'}))

server/templates/server/author-profile.html
{% extends 'server/technical/pattern.html' %}
{% load static %}

{% block title %}{{ data.title }}{% endblock %}
    {% block content %}
            <div class="row mbn-50">
                <!--Author Top Start-->
                <div class="col-12 mb-50">
                    <div class="author-top">
                        <div class="inner">
                            <div class="author-profile">
                                <div class="image">
                                    <img src="{% static 'server/assets/images/avatar/profile.jpg' %}" class="d-none" alt="">
                                    <h2>MH</h2>
                                    <button class="edit"><i class="zmdi zmdi-cloud-upload"></i>Change Image</button>
                                </div>
                                <div class="info">
                                    <h5>{{ user.username }}</h5>
                                    <span>Мой тариф: {{ user.flesh.tariff.name }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Author Top End-->

                <!--Timeline / Activities Start-->

                <!--Timeline / Activities End-->
                <div class="col-md-6 col-12 mb-30">
                    <div class="box">
                        <div class="box-head">
                            <h4 class="title">Ваш реферальный код!</h4>
                        </div>
                        <div class="box-body">
                            <p>Lorem ipsum dolor sit amet, consectetur <span id="paragraphClipboard2" class="fw-700 text-primary">http://localhost:8000/register?ref={{ user.rif_token }}</span>. Quidem porro reiciendis odio in cumque omnis fuga iusto ipsam asperiores nesciunt officia officiis labore laboriosam aperiam deleniti consequatur debitis, ea. Veniam.</p>
                            <button class="button button-primary button-clipboard mb-0 mt-15" data-clipboard-target="#paragraphClipboard2">Copy</button>
                        </div>
                    </div>
                </div>

                <div class="col-xlg-12 col-lg-6 col-12 mb-30">

                            <div class="box">
                                <div class="box-head">
                                    <h3 class="title">История финансовых операций</h3>
                                </div>
                                <div class="box-body">
                                    <div class="table-responsive">
                                        <table class="table">

                                            <!-- Table Head Start -->
                                            <thead>
                                                <tr>
                                                    <th>Наименование</th>
                                                    <th>Комментарий к платежу</th>
                                                    <th>Статус</th>
                                                    <th>Стоимость</th>
                                                </tr>
                                            </thead><!-- Table Head End -->

                                            <!-- Table Body Start -->
                                            <tbody>
                                            {% for el in payments %}
                                                <tr>
                                                    {% if el.category == 'update' %}
                                                        <td class="text-danger fw-600">{{ el.get_category_display  }}</td>
                                                    {% elif el.category == 'purchase_bonuses' %}
                                                        <td class="text-warning fw-600">{{ el.get_category_display  }}</td>
                                                    {% elif el.category == 'purchase' %}
                                                        <td class="text-success fw-600">{{ el.get_category_display  }}</td>
                                                    {% elif el.category == 'enrollment' %}
                                                        <td class="text-success fw-600">{{ el.get_category_display  }}</td>
                                                    {% elif el.category == 'withdrawal' %}
                                                        <td class="text-success fw-600">{{ el.get_category_display  }}</td>
                                                    {% endif %}
                                                    <td>
                                                        <p>{{ el.dsc }}</p>
                                                    </td>
                                                    {% if el.get_status_display == 'В ожидании'%}
                                                    <td><span class="text-info d-flex justify-content-between fw-600">{{ el.get_status_display }}</span></td>
                                                    {% elif el.get_status_display == 'Отклонен' or el.get_status_display == 'Заблокирован' or el.get_status_display == 'Неуспешный' %}
                                                    <td><span class="text-danger d-flex justify-content-between fw-600">{{ el.get_status_display }}</span></td>
                                                    {% elif el.get_status_display == 'Отменен' or el.get_status_display == 'Возврат' %}
                                                    <td><span class="text-warning d-flex justify-content-between fw-600">{{ el.get_status_display }}</span></td>
                                                    {% elif el.get_status_display == 'В обработке' or el.get_status_display == 'На проверке' %}
                                                    <td><span class="text-secondary d-flex justify-content-between fw-600">{{ el.get_status_display }}</span></td>
                                                    {% elif el.get_status_display == 'Успешный' %}
                                                    <td><span class="text-success d-flex justify-content-between fw-600">{{ el.get_status_display }}</span></td>
                                                    {% endif %}
                                                    <td><span class="text-success d-flex justify-content-between fw-600">{{ el.price }} ₽<span class="tippy ml-10" data-tippy-content="Операция была завершена <br/> {{ el.date }}."><i class="zmdi zmdi-info-outline"></i></span></span></td>
                                                </tr>
                                            {% endfor %}

                                            </tbody><!-- Table Body End -->
                                        </table>
                                    </div>
                                </div>
                                <div class="col-12 mb-15 d-flex justify-content-end mb-3" >
                                    <a href="{% url 'payment_history' %}" class="button button-warning">Подробнее</a>
                                </div>
                            </div>

                        </div>
                <!--Right Sidebar Start-->
                <div class="col-xlg-8 col-12 mb-50">
                    <div class="row mbn-30">

                        <!--Author Information Start-->
                        <div class="col-12 mb-30">
                    <div class="box">
                        <div class="box-head">
                            <h3 class="title">Техподдержка</h3>
                        </div>
                        <div class="box-body">

                            <div class="smart-wizard">
                                <ul>
                                    <li><a href="#step-1">Проблемы с сайтом</a></li>
                                    <li><a href="#step-2">Проблема с IDF</a></li>
                                    <li><a href="#step-3">Финансовый вопрос</a></li>
                                    <li><a href="#step-4">Иное</a></li>
                                </ul>

                                <div>
                                    <div id="step-1">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            <div class="row mbn-20">
                                                <div class="col-12 mb-20">
                                                    <h4>Проблемы с сайтом</h4>
                                                </div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.name }}</div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.mail }}</div>
                                                <div class="col-12 mb-20">{{ form.dsc }}</div>
                                                <div class="col-12 mb-20">{{ catForm.category_site }}</div>
                                                <button type="submit" class="button button-primary col-lg-3 col-6 mb-20">Отправить заявление</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div id="step-2">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            <div class="row mbn-20">
                                                <div class="col-12 mb-20">
                                                    <h4>Проблема с IDF</h4>
                                                </div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.name }}</div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.mail }}</div>
                                                <div class="col-12 mb-20">{{ form.dsc }}</div>
                                                <div class="col-12 mb-20">{{ catForm.category_idf }}</div>
                                                <button type="submit" class="button button-primary col-lg-3 col-6 mb-20">Отправить заявление</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div id="step-3">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            <div class="row mbn-20">
                                                <div class="col-12 mb-20">
                                                    <h4>Финансовый вопрос</h4>
                                                </div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.name }}</div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.mail }}</div>
                                                <div class="col-12 mb-20">{{ form.dsc }}</div>
                                                <div class="col-12 mb-20">{{ catForm.category_money }}</div>
                                                <button type="submit" class="button button-primary col-lg-3 col-6 mb-20">Отправить заявление</button>
                                            </div>
                                        </form>
                                    </div>
                                    <div id="step-4">
                                        <form action="#" method="post">
                                            {% csrf_token %}
                                            <div class="row mbn-20">
                                                <div class="col-12 mb-20">
                                                    <h4>Иное</h4>
                                                </div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.name }}</div>
                                                <div class="col-lg-6 col-12 mb-20">{{ form.mail }}</div>
                                                <div class="col-12 mb-20">{{ form.dsc }}</div>
                                                <div class="col-12 mb-20">{{ catForm.category_other }}</div>
                                                <button type="submit" class="button button-primary col-lg-3 col-6 mb-20">Отправить заявление</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                    </div>
                </div>
                <!--Right Sidebar End-->

            </div>

        </div><!-- Content Body End -->


      {% endblock %}

<script>
   $('.smart-wizard').smartWizard({
    showStepURLhash: false,
});

FilePond.registerPlugin(FilePondPluginImageExifOrientation, FilePondPluginImagePreview);
const inputElement = document.querySelector('.file-pond');
const pond = FilePond.create( inputElement, {
    imagePreviewHeight: 140,
});
</script>

server/templates/server/news.html
{% extends 'server/technical/pattern.html' %}
{% load static %}
{% block title %}{{ data.title }}{% endblock %}
{% block content %}

<div class="row">
{% for new in news %}
<div class="col-lg-6 col-12 mb-30">
                    <div class="box">
                        <div class="box-body">
                            <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <img src="{% static 'server/assets/images/carousel/carousel-7.jpg' %}" alt="...">
                                        <div class="carousel-caption">
                                            <a href="{% url 'detail_news' new.id %}" class="text-white">{{ new.title }}</a>
                                            <p>{{ new.subtitle }}</p>
                                        </div>
                                    </div>
                                </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

{% endfor %}
</div>

{% endblock %}